services:
  mysql:
    image: mysql:8.0
    container_name: botanify-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: botanify
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      
  redis-master:
    image: redis:7.0
    hostname: redis-master
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/data:/data
    networks:
      - app-network
    environment:
      TZ: Asia/Seoul
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    command: redis-server --save 20 1 --loglevel warning

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      EDGE_PORT: 4566
      DEBUG: 1
      DATA_DIR: /var/lib/localstack/data
      AWS_DEFAULT_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin
      PERSISTENCE: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/var/lib/localstack
      - ./aws:/etc/localstack/init/ready.d
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
  localstack-data: