global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-1'
    static_configs:
      - targets: ['3.39.43.235:8080']
        labels:
          application: 'spring-1'

  - job_name: 'spring-2'
    static_configs:
      - targets: ['15.165.192.37:8080']
        labels:
          application: 'spring-2'

  - job_name: 'nginx'
    static_configs:
      - targets: ['43.202.147.203:9113']
        labels:
          instance: 'nginx'